config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  resources :vehicles, only: [:index, :show, :new, :create] do
    resources :bookings, only: [:create]
    resources :reviews, only: [:create]
  end
  resources :bookings, only: [:index, :update]
  namespace :owner do
    resources :bookings, only: [:index]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :vehicle
  validates :start_date, presence: true
  validates :return_date, presence: true
  validates :status, presence: true
  validate :check_dates
  enum status: { pending: 0, accepted: 1, rejected: 2 }

  def check_dates
    errors.add(:return_date, "End date should be before start date") if return_date < start_date
  end
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  belongs_to :vehicle
  validates :content, presence: true
  RATINGS = [1, 2, 3, 4, 5]
  validates :rating, presence: true, inclusion: { in: RATINGS }, numericality: { only_integer: true }
end

app/models/user.rb
class User < ApplicationRecord
  has_many :bookings, dependent: :destroy
  has_many :vehicles, dependent: :destroy
  has_many :reviews, dependent: :destroy
  has_many :bookings_as_owner, through: :vehicles, source: :bookings
  has_one_attached :photo
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/vehicle.rb
class Vehicle < ApplicationRecord
  belongs_to :user
  has_many :bookings, dependent: :destroy
  has_many :reviews, dependent: :destroy
  has_one_attached :photo

  CATEGORIES = ['Itasha', 'Decotora', 'Bosozoku_Bike']

  validates :brand, presence: true
  validates :model, presence: true
  validates :category, inclusion: { in: CATEGORIES }
  validates :location, presence: true
  validates :price, presence: true
  validates :description, presence: true
  # geocoding
  geocoded_by :location
  after_validation :geocode, if: :will_save_change_to_location?

  include PgSearch::Model
  pg_search_scope :search_by_category_and_location,
                  against: [:category],
                  using: {
                    tsearch: { prefix: true } # <-- now `superman batm` will return something!
                  }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # [...]
  before_action :authenticate_user!
  include Pundit

  # Pundit: white-list approach.
  after_action :verify_authorized, except: :index, unless: :skip_pundit?
  after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

  # Uncomment when you *really understand* Pundit!
  # rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
  # def user_not_authorized
  #   flash[:alert] = "You are not authorized to perform this action."
  #   redirect_to(root_path)
  # end

  private

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def index
    @bookings = policy_scope(Booking)
  end

  def create
    @vehicle = Vehicle.find(params[:vehicle_id])
    @booking = Booking.new(booking_params)
    @booking.user = current_user
    @booking.vehicle = @vehicle

    authorize @booking
    if @booking.save
      redirect_to bookings_path
    else
      # render "vehicles/show"
      redirect_to vehicle_path(@vehicle), notice: @booking.errors.messages[:return_date].first
    end
  end

  def update
    @booking = Booking.find(params[:id])
    authorize @booking
    if @booking.update(booking_params)
      respond_to do |format|
        format.html { redirect_to owner_bookings_path(anchor: "booking-#{@booking.id}"), notice: 'Booking was succesfully updated.' }
        format.js # look for a JS view with the same action name
      end
    else
      render :edit
    end
  end

  private

  def booking_params
    params.require(:booking).permit(:start_date, :return_date, :status)
  end
end

app/controllers/owner/bookings_controller.rb
class Owner::BookingsController < ApplicationController
  def index
    @bookings = policy_scope([:owner, Booking])

  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home

  def home
    @vehicles = Vehicle.all
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def create
    @review = Review.new(review_params)
    @review.user = current_user
    @vehicle = Vehicle.find(params[:vehicle_id])
    @review.vehicle = @vehicle
    authorize @review
    if @review.save
      respond_to do |format|
        format.html { redirect_to vehicle_path(@review.vehicle, anchor: "review-#{@review.id}") }
        format.js # look for a JS view with the same action name
      end
    else
      render :new
    end
  end

  private

  def review_params
    params.require(:review).permit(:rating, :content)
  end
end

app/controllers/vehicles_controller.rb
class VehiclesController < ApplicationController
  skip_before_action :authenticate_user!, only: %i[index show]
  # before_action :set_vehicle, only: [:show]

  def index
    @vehicles =
      if params[:category].present?
        policy_scope(Vehicle).search_by_category_and_location(params[:category])
      else
        policy_scope(Vehicle)
      end
    @vehicles = @vehicles.near(params[:location], 50) if params[:location]
    @markers = @vehicles.geocoded.map do |vehicle|
      {
        lat: vehicle.latitude,
        lng: vehicle.longitude,
        info_window: render_to_string(partial: "info_window", locals: { vehicle: vehicle })
      }
    end
  end

  def show
    @booking = Booking.new
    @vehicle = Vehicle.find(params[:id])
    @reviews = Review.where(vehicle: @vehicle.id)
    @review = Review.new
    authorize @vehicle
    # authorize @reviews
  end

  def new
    @vehicle = Vehicle.new
    authorize @vehicle
  end

  def create
    @vehicle = Vehicle.new(vehicle_params)
    @vehicle.user = current_user
    authorize @vehicle

    if @vehicle.save
      redirect_to vehicle_path(@vehicle)
    else
      render :new
    end
  end

  private

  def vehicle_params
    params.require(:vehicle).permit(:brand, :model, :category, :description, :price, :location, :photo)
  end

  # def set_vehicle
  #   @vehicle = Vehicle.find(params[:id])
  #   authorize @vehicle
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/_booking.html.erb
<div class="bookings">
  <% @bookings.each do |booking| %>
    <%= render "owner/bookings/card", booking: booking %>
  <% end %>
</div>

app/views/bookings/_guest_status.html.erb
<div class="d-flex justify-content-between">
  <% if booking.status == "pending" %>
    <h2 style="color:black">Pending</h2>
  <% elsif booking.status == "accepted" %>
    <h2 style="color:green">Accepted</h2>
  <% else %>
    <h2 style="color:red">Rejected</h2>
  <% end %>
</div>

app/views/bookings/index.html.erb
<div class="container d-flex justify-content-center mt-4">
  <h1>You have <%= @bookings.count %> <%= "booking".pluralize(@bookings.count) %> 🗓</h1>
</div>
<%= render 'booking' %>

app/views/bookings/update.js.erb
function updateCard() {
const card = document.querySelector("#booking-<%= @booking.id %>")
card.outerHTML = "<%= j render 'owner/bookings/card', booking: @booking %>"
}
updateCard();

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NinjaGarage</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>
  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
    <%= yield %>
    <%= render 'shared/footer' %>
  </body>
</html>

app/views/layouts/devise.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NinjaGarage</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>
  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
    <div class="container">
      <div class="row">
        <div class="col-6">
          <%= yield %>
        </div>
      </div>
    </div>
  </body>
</html>

app/views/owner/bookings/_card.html.erb
<% booking.status == "accepted"? card_color="green": card_color=""%>
<% start_date = booking.start_date %>
<% return_date = booking.return_date %>
<% total = booking.vehicle.price * (return_date - start_date).to_i %>
<div class="container">
  <div class="row">
    <div class="p-0 card-owner-booking <%=card_color%> mt-5" id="booking-<%= booking.id %>">
      <div class="owner-booking-card d-flex justify-content-between align-items-center">
        <!--div class="card-booking-picture" style="color:white; background-image: url(<%= cl_image_path(booking.vehicle.photo.key)%>)"></div><-->
        <%= link_to vehicle_path(booking.vehicle) do %>
          <%= cl_image_tag booking.vehicle.photo.key, width: 300, height: 200, crop: :fill %>
          <div class="container">
            <h2 style="text-align:left"><%= booking.vehicle.brand %> : <%= booking.vehicle.model %></h2>
            <p><i class="fas fa-calendar-alt"></i> <%= booking.start_date %> <i class="fas fa-angle-double-right"></i> <%= booking.return_date %></p>
            <p><i class="fas fa-map-marker-alt"></i> <%= booking.vehicle.location %></p>
            <% if booking.vehicle.user == current_user %>
              <p><i class="fas fa-user"></i> <%= booking.user.first_name %> <%= booking.user.last_name %></p>
            <% else %>
              <p><i class="fas fa-user-check"></i> <%= booking.vehicle.user.first_name %> <%= booking.vehicle.user.last_name %>
              </p>
            <% end %>
          <% end %>
        </div>
        <div class="mx-4">
          <% if booking.vehicle.user == current_user %>
            <%= render "owner/bookings/owner_status", booking: booking %>
          <% else %>
            <%= render "bookings/guest_status", booking: booking %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/owner/bookings/_owner_booking.html.erb
<div class="bookings">
  <% @bookings.each do |booking| %>
    <%= render "owner/bookings/card", booking: booking%>
  <% end %>
</div>

app/views/owner/bookings/_owner_status.html.erb
<div>
  <% if booking.status == "pending" %>
    <div class="container px-0">
      <%= simple_form_for booking, remote: true do |f| %>
        <%= f.input :status, as: :hidden, input_html:{value:"accepted"} %>
        <%= f.submit "accept", class: 'btn btn-primary btn-lg w-100' %>
      <% end %>
    </div>
    <div class="container px-0">
      <%= simple_form_for booking, remote: true do |f| %>
        <%= f.input :status, as: :hidden, input_html:{value:"rejected"} %>
        <%= f.submit "decline", class: 'btn btn-danger btn-lg w-100' %>
      <% end %>
    </div>
  <% elsif booking.status == "accepted" %>
    <h2 style="color:green">Accepted</h2>
  <% else %>
    <h2 style="color:red">Rejected</h2>
  <% end %>
</div>

app/views/owner/bookings/index.html.erb
<div class="container d-flex justify-content-center mt-4">
  <h1>You have <%= @bookings.count %> <%= "booking".pluralize(@bookings.count) %> from customers🗓</h1>
</div>
<div class="container d-flex justify-content-center">
  <p>Accept or Reject pending bookings for your vehicles</p>
</div>
<%= render 'owner_booking' %>
</div>

app/views/pages/home.html.erb
<div class="banner">
  <div class="container">
    <h1>Ninja Garage</h1>
    <p>Rent crazy vehicles</p>
    <a class="btn" href="vehicles#index"> Browse vehicles </a>
  </div>
  <div class="arrow">
    <a href="#browse"><i class="fas fa-chevron-down"></i></a>
  </div>
</div>
<div id="browse" class="container pt-5">
  <div class="container py-5">
    <div>
      <h1 class='slogan text-center'>Be a yankee for a day</h1>
    </div>
  </div>
  <h3 class='mt-6 p-3'>Browse by Category</h3>
  <div class="categories">
    <%= link_to vehicles_path(category: "Decotora") do %>
      <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://mulattodiaries.files.wordpress.com/2010/02/decotora.jpg)">
        <h2>Decotoras</h2>
      </div>
    <% end %>
    <%= link_to vehicles_path(category: "Bosozoku_bike") do %>
      <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://4.bp.blogspot.com/-VcQ0QHojFFk/UZZPCBbE1LI/AAAAAAAANrA/UGp06WUYaAk/s1600/bosozoku+bike.JPG)">
        <h2>Bosozoku Bikes</h2>
      </div>
    <% end %>
    <%= link_to vehicles_path(category: "Itasha") do %>
      <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://i.ebayimg.com/images/g/qmkAAOSwInxXNREG/s-l500.jpg)">
        <h2>Itashas</h2>
      </div>
    <% end %>
  </div>
  <h1>Suggestions:</h1>
</div>
<%= render "vehicles/car_cards_home" %>

app/views/reviews/_review.html.erb
<div class="d-flex align-items-center stars-show pb-2" id="review-<%= review.id %> review_content">
  <div class="username me-3">
    <%= review.user.first_name %>
    <%= review.user.last_name %>
  </div>
  <% review.rating.times do %>
    <i class="fas fa-star"></i>
  <% end %>
  <% (5 - review.rating).times do %>
    <i class="far fa-star"></i>
  <% end %>
</div>
<p><%= review.content %></p>

app/views/reviews/create.js.erb
console.log("pepe"); <%# useless line, just to check if this js file is received by the browser %>
<%# only is old way to define js functions %>
function insertReview() {
const reviews = document.querySelector('#reviews');
reviews.insertAdjacentHTML('beforeend', "<%= j render 'reviews/review', review: @review %>")
}
function emptyForm() {
document.getElementById("review_content").value = "";
}
insertReview();
emptyForm();

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer-basic">
  <footer>
    <ul class="list-inline">
      <li class="list-inline-item"><%= link_to "Home", root_path %></li>
      <li class="list-inline-item"><%= link_to "Vehicles", vehicles_path %></li>
      <li class="list-inline-item"><%= link_to "Bookings", bookings_path %></li>
      <li class="list-inline-item"><%= link_to "Add vehicle", new_vehicle_path %></li>
      <li class="list-inline-item"><a href="https://github.com/tirsop/ninja-garage" target="_blank">Github Repository</a></li>
    </ul>
    <div class="madeby">
      <p>App made by</p>
    </div>
    <div class="social"><a class="footer-img" href="https://github.com/tirsop" target="_blank"><%= image_tag 'tirso.png' %></a><a class="footer-img" href="https://github.com/KenjiYANAGAWA" target="_blank"><%= image_tag 'kenji.jpg' %></a><a class="footer-img" href="https://github.com/yharwood" target="_blank"><%= image_tag 'yuki.jpg' %></a><a class="footer-img" href="https://github.com/luisrrv" target="_blank"><%= image_tag 'luis.jpg' %></a></div>
    <p class="copyright">Ninja Garage © 2022</p>
  </footer>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to root_path, class: "navbar-brand" do %>
      <%= image_tag "logo.png" %>
    <% end %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <%# <li class="nav-item active nav-link">
            <%= link_to "+ Vehicle", new_vehicle_path %>
          <%# </li> %>
          <li class="nav-item active nav-link">
            <%= current_user.first_name %>
          </li>
          <li class="nav-item active">
            <%# <%= link_to "Home", "#", class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%# <%= link_to "Messages", "#", class: "nav-link" %>
          </li>
          <li class="nav-item dropdown">
            <%= image_tag "tirso.png", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <p class="dropdown-item"><%= current_user.email %></p>
              <%= link_to bookings_path do %>
                <p class="dropdown-item"><%= "Bookings: #{current_user.bookings.count}" %></p>
              <% end %>
              <%= link_to owner_bookings_path do %>
                <p class="dropdown-item"><%= "Vehicles: #{current_user.vehicles.count}" %></p>
              <% end %>
              <%= link_to "Add a vehicle", new_vehicle_path, class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
          <li>
            <%= link_to "Sign up", new_user_registration_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/vehicles/_car_cards.html.erb
<div class="content">
  <div class="cards">
    <% @vehicles.shuffle.each do |vehicle| %>
      <%= link_to vehicle_path(vehicle) do  %>
        <div class="card-trip">
          <%= cl_image_tag(vehicle.photo.key) %>
          <div class="card-trip-infos">
            <div>
              <h2><%= vehicle.brand %></h2>
              <p><%= vehicle.model %></p>
            </div>
            <h3 class="card-trip-pricing"><%= number_to_currency(vehicle.price, {unit: '¥', precision: 0}) %><span class="pricing-day"> / day</span></h3>
          </div>
        </div>
      <% end %>
    <% end %>
  </div>
</div>

app/views/vehicles/_car_cards_home.html.erb
<div class="content">
  <div class="cards-home">
    <% @vehicles.shuffle.each do |vehicle| %>
      <%= link_to vehicle_path(vehicle) do  %>
        <div class="card-trip">
          <%= cl_image_tag(vehicle.photo.key) %>
          <div class="card-trip-infos">
            <div>
              <h2><%= vehicle.brand %></h2>
              <p><%= vehicle.model %></p>
            </div>
            <h3 class="card-trip-pricing"><%= number_to_currency(vehicle.price, {unit: '¥', precision: 0}) %><span class="pricing-day"> / day</span></h3>
          </div>
        </div>
      <% end %>
    <% end %>
  </div>
</div>

app/views/vehicles/_info_window.html.erb
<%= link_to vehicle_path(vehicle), class: 'maplink' do %>
  <div class="container info-window">
    <%= cl_image_tag(vehicle.photo.key) %>
    <h3><strong><%= "#{vehicle.brand} #{vehicle.model}" %></strong></h3>
    <p><%= vehicle.category %></p>
    <p><%= vehicle.location %></p>
    <h5><%= "#{number_to_currency(vehicle.price, {unit: '¥', precision: 0})} / day" %></h5>
    <%# link to not wrking %>
    <%# <%= link_to "See more about #{vehicle.model}", vehicle_path(vehicle) %>
  </div>
<% end %>
<%# Go to assets/componets/_map to change style %>

app/views/vehicles/_marker.html.erb
<%= image_tag 'avatar.jpg' %>

app/views/vehicles/index.html.erb
<div class="container d-flex justify-content-center">
  <h1 class="slogan text-center p-5">🎌 All of our vehicles 🎌</h1>
</div>
<div class="container">
  <div class="row justify-content-center pb-5">
    <div class="col-12 col-sm-8 col-lg-6">
      <%= form_tag vehicles_path, method: :get, class:'d-flex' do %>
        <%= select_tag :category,
            options_for_select(Vehicle::CATEGORIES, params[:category]),
            class: "form-control search1",
            prompt: "Vehicle Type"
        %>
        <%= text_field_tag :location,
            params[:location],
            class: "form-control search2",
            placeholder: "Location"
        %>
        <%= submit_tag "Search", class: "btn btn-danger booking-more-btn" %>
      <% end %>
    </div>
  </div>
  <div class="d-flex">
    <%= render "car_cards" %>
    <div class="mapita"
      data-controller="mapbox"
      data-mapbox-markers-value="<%= @markers.to_json %>"
      data-mapbox-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
    </div>
  </div>
</div>

app/views/vehicles/new.html.erb
<h1 class="slogan p-3">Rent out your vehicle!</h1>
<div class="container p-3">
  <div class="row">
    <div class="col-12 col-sm-6 offset-sm-3">
      <%= simple_form_for(@vehicle) do |f| %>
        <%= f.input :brand %>
        <%= f.input :model %>
        <%= f.input :category, collection: Vehicle::CATEGORIES, include_blank: false %>
        <%= f.input :description %>
        <%= f.input :price %>
        <%= f.input :location %>
        <%= f.input :photo, as: :file %>
        <%= f.submit class: 'btn btn-danger mt-2' %>
      <% end %>
    </div>
  </div>
</div>

app/views/vehicles/show.html.erb
<div class="container">
  <div class="item card-category" style="height: 600px; background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(<%= @vehicle.photo.attached? ? cl_image_path(@vehicle.photo.key) : image_path('https://st3.depositphotos.com/23594922/31822/v/600/depositphotos_318221368-stock-illustration-missing-picture-page-for-website.jpg') %>)">
  </div>
  <div class="d-flex mt-3">
    <div>
      <h1 class="vehicle-title"><%= @vehicle.brand %> <%= @vehicle.model %></h1>
      <p class="text-danger"><%= @vehicle.category %></p>
      <div class="content con</div>p-3">
        <div class="row position-relative">
          <div class="col m-3">
            <div>
              <p><strong>Brand</strong>    : <%= @vehicle.brand %></p>
              <p><strong>Model</strong>    : <%= @vehicle.model %></p>
              <p><strong>Location</strong> : <%= @vehicle.location %></p>
              <p><strong>Category</strong> : <%= @vehicle.category %></p>
              <p><strong>Other features:</strong></p>
              <p><%= @vehicle.description %></p>
            </div>
            <%# -------------OWNER INFO------------- %>
            <div class="notification my-5">
              <%= image_tag "avatar.jpg", class: "avatar-large" %>
              <div class="notification-content">
                <p><small>Owner</small></p>
                <p><%= "#{@vehicle.user.first_name} #{@vehicle.user.last_name}" %></p>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <%# -------------BOOKING FORM------------- %>
    <div data-controller="calculation" class="col-xs-12 col-sm-5" >
      <div class="comment-form m-3 p-3" id="book">
        <h2>Rent this vehicle</h2>
        <div class="vehicle-book-form">
          <p class="vehicle-price"><%= number_to_currency(@vehicle.price, {unit: '¥', precision: 0}) %> / day</p>
          <%= simple_form_for [@vehicle, @booking] do |f| %>
            <%= f.input :start_date, html5: true, input_html:{data:{calculation_target:"startDate"}, min: Date.today} %>
            <%= f.input :return_date, html5: true, input_html:{data:{calculation_target:"returnDate", action:"change->calculation#calculate"}, min: Date.today} %>
            <div class="total-price my-3">
              <strong>
                ¥<span data-calculation-target="price"><%= @vehicle.price %></span> x <span data-calculation-target="days">1</span>days = ¥<span data-calculation-target="total"><%= @vehicle.price %></span>
              </strong>
            </div>
            <div class="d-grid"><%= f.submit 'Book', class: 'btn btn-danger rounded-pill py-2 my-2' %></div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
  <%# -------------OTHER VEHICLES OF THE OWNER------------- %>
  <div class="p-3 mt-4">
    <h3><%= "#{@vehicle.user.first_name}'s Vehicles" %></h3>
    <div class="cards">
      <% @vehicle.user.vehicles.each do |vehicle| %>
        <%= link_to vehicle_path(vehicle) do %>
          <div class="card-trip">
            <%= cl_image_tag(vehicle.photo.key) %>
            <div class="card-trip-infos">
              <div>
                <h2><%= vehicle.brand %></h2>
                <p><%= vehicle.model %></p>
              </div>
              <h2 class="card-trip-pricing"><%= number_to_currency(vehicle.price, {unit: '¥', precision: 0}) %></h2>
            </div>
          </div>
        <% end %>
      <% end %>
    </div>
  </div>
  <%# -------------LIST OF REVIEWS-------------- %>
  <div class="p-3 m-3">
    <h3>Reviews</h3>
    <div id="reviews">
      <% if @vehicle.reviews.blank? %>
        Be the first to review for this <%= @vehicle.brand %>!
      <% else %>
        <% @vehicle.reviews.each do |review| %>
          <%= render 'reviews/review', review: review %>
        <% end %>
      <% end %>
    </div>
  </div>
  <%# -------------FORM FOR THE REVIEWS-------------- %>
  <div class="comment-form p-5 m-3">
    <h3>How was your experience?</h3>
    <%=  simple_form_for [@vehicle, @review], remote: true do |f| %>
      <div class="star-rating mb-5">
        <% 5.times do |i| %>
          <input type="radio" name="review[rating]" value="<%= i + 1 %>" <%= "checked" if i == 2 %> />
        <% end %>
      </div>
      <%= f.input :content, label: false %>
      <%= f.submit 'Post', class: 'btn btn-primary' %>
    <% end %>
  </div>
</div>